test accuracy workflow

diff --git a/.github/workflows/test_single_npu.yaml b/.github/workflows/test_single_npu.yaml
--- a/.github/workflows/test_single_npu.yaml
+++ b/.github/workflows/test_single_npu.yaml
@@ -1,14 +1,27 @@
-name: 'single_npu_test'
+name: 'accuracy test'
 
 on:
   workflow_dispatch:
     inputs:
+      branch:
+        description: 'choose a new dev branch'
+        required: true
+      models:
+        description: 'choose model(all/Qwen/Qwen2.5-7B-Instruct/meta-llama/Llama-3.1-8B-Instruct/Qwen/Qwen2.5-VL-7B-Instruct)'
+        required: true
+        type: choice
+        options:
+          - all
+          - Qwen/Qwen2.5-7B-Instruct
+          - meta-llama/Llama-3.1-8B-Instruct
+          - Qwen/Qwen2.5-VL-7B-Instruct
+        default: 'all'
       runner:
         required: true
         type: choice
         options:
-          - linux-arm64-npu-1
-        default: 'linux-arm64-npu-1'
+          - linux-arm64-npu-4 
+        default: 'linux-arm64-npu-4'
         description: 'The runner selected to run on'
       image:
         required: true
@@ -17,17 +30,7 @@ on:
           - ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10
         default: 'ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10'
         description: 'The docker image which will be loaded'
-  # workflow_call:
-  #   inputs:
-  #     runner:
-  #       required: true
-  #       type: string
-  #       description: 'The runner selected to run on'
-  #     image:
-  #       required: true
-  #       type: string
-  #       description: 'The docker image which will be loaded'
-
+    
 # Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
 # declared as "shell: bash -el {0}" on steps that need to be properly activated.
 # It's used to activate ascend-toolkit environment variables.
@@ -36,9 +39,10 @@ defaults:
     shell: bash -el {0}
 
 jobs:
-  benchmark:
-    name: run benchmarks for torch_npu
-    runs-on: ${{ github.event.inputs.runner || 'linux-arm64-npu-1' }}
+  test:
+    name: vLLM Ascend accuracy test (self-host)
+    runs-on: ${{ github.event.inputs.runner || 'linux-arm64-npu-4' }}
+    timeout-minutes: 1000
     container:
       image: ${{ github.event.inputs.image }}
       env:
@@ -48,87 +52,101 @@ jobs:
         ES_OM_DOMAIN: ${{ secrets.ES_OM_DOMAIN }}
         ES_OM_AUTHORIZATION: ${{ secrets.ES_OM_AUTHORIZATION }}
     steps:
-      - name: Show NPU info
+      - name: Validate branch name
+        id: validate_branch
+        run: |
+          if [[ "${{ github.event.inputs.branch }}" =~ -dev$ ]]; then
+            echo "Branch name is valid."
+          else
+            echo "Error: The selected branch does not end with '-dev'."
+            exit 1
+          fi
+          SANITIZED_BRANCH_NAME="${{ github.event.inputs.branch }}"
+          echo "SANITIZED_BRANCH_NAME=${SANITIZED_BRANCH_NAME}" >> $GITHUB_ENV
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.branch }}
+
+      - name: Check npu and CANN info
         run: |
           npu-smi info
-      - name: Check env
-        run: |
-          echo "hf_endpoint: $HF_ENDPOINT"
-          echo "hf_token: $HF_TOKEN"
-          echo "hf: ${{ secrets.HF_TOKEN }}"
-                  
+          cat /usr/local/Ascend/ascend-toolkit/latest/"$(uname -i)"-linux/ascend_toolkit_install.info
+
       - name: Config mirrors
         run: |
           sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
           pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
+          apt-get update -y
+          apt install git -y
+          git config --global url."https://gh-proxy.test.osinfra.cn/https://github.com/".insteadOf https://github.com/
+
+      - name: Checkout vllm-project/vllm-ascend repo
+        uses: actions/checkout@v4
 
       - name: Install system dependencies
         run: |
-          apt-get update -y
-          apt-get -y install git jq wget curl lsof
-
-      # See: https://github.com/actions/checkout/issues/363#issuecomment-1915075699
-      # See: https://github.com/hunshcn/gh-proxy/issues/28#issuecomment-773769630
-      - name: Config git
-        run: |
-          git config --global --add safe.directory "$GITHUB_WORKSPACE"
-          git config --global url."https://gh-proxy.test.osinfra.cn/https://github.com/".insteadOf https://github.com/
+          apt-get -y install `cat packages.txt`
 
       - name: Checkout vllm-project/vllm repo
         uses: actions/checkout@v4
         with:
           repository: vllm-project/vllm
           ref: v0.7.3
-          path: ./
-          
+          path: ./vllm-empty
+
+      - name: Install vllm-project/vllm from source
+        working-directory: ./vllm-empty
+        run: |
+          VLLM_TARGET_DEVICE=empty pip install -e .
+
       - name: Checkout vllm-project/vllm-ascend repo
         uses: actions/checkout@v4
         with:
           repository: vllm-project/vllm-ascend
           path: ./vllm-ascend
-          ref: v0.7.3rc1
+          ref: v0.7.3rc2  
           fetch-depth: 0
-
-      - name: Checkout open-compass/opencompass repo
-        uses: actions/checkout@v4
-        with:
-          repository: open-compass/opencompass
-          path: ./opencompass
-          fetch-depth: 0
-
-      - name: Install vllm-project/vllm from source
-        run: |
-          VLLM_TARGET_DEVICE=empty pip install -e .
 
       - name: Install vllm-project/vllm-ascend
         working-directory: ./vllm-ascend
         run: |
+          pip uninstall -y numpy
+          pip install -r requirements-dev.txt
           pip install -e .
-      
-      - name: Install development tools
-        run: |
-          apt-get update && apt-get install -y build-essential cmake g++
-
-      - name: Install open-compass/opencompass
-        working-directory: ./opencompass
-        run: |
-          pip install -U opencompass
 
       - name: Install pta
         run: |
-          mkdir pta
-          cd pta
-          wget https://pytorch-package.obs.cn-north-4.myhuaweicloud.com/pta/Daily/v2.5.1/20250308.3/pytorch_v2.5.1_py310.tar.gz
-          tar -xvf pytorch_v2.5.1_py310.tar.gz
-          pip install ./torch_npu-2.5.1.dev20250308-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
-          cd ..
-          rm -rf pta
+          if [ ! -d /root/.cache/pta ]; then
+            mkdir -p /root/.cache/pta
+          fi
 
+          if [ ! -f /root/.cache/pta/torch_npu-2.5.1.dev20250320-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl ]; then
+            cd /root/.cache/pta
+            rm -rf pytorch_v2.5.1_py310*
+            wget https://pytorch-package.obs.cn-north-4.myhuaweicloud.com/pta/Daily/v2.5.1/20250320.3/pytorch_v2.5.1_py310.tar.gz
+            tar -zxvf pytorch_v2.5.1_py310.tar.gz
+          fi
+
+          pip install /root/.cache/pta/torch_npu-2.5.1.dev20250320-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
+
+      - name: Checkout EleutherAI/lm-evaluation-harness repo
+        uses: actions/checkout@v4
+        with:
+          repository: EleutherAI/lm-evaluation-harness
+          path: ./lm-eval
+          fetch-depth: 0
+
+      - name: Install EleutherAI/lm-evaluation-harness
+        working-directory: ./lm-eval
+        run: |
+          pip install -e .
+      
       - name: Checkout nv-action/vllm-benchmarks repo
         uses: actions/checkout@v4
         with:
           repository: nv-action/vllm-benchmarks
-          fetch-depth: 0
           path: ./vllm-benchmarks
       
       - name: Install benchmark dependencies
@@ -136,12 +154,65 @@ jobs:
         run: |
           pip install -r requirements.txt
 
-      - name: Copy file to opencompass directory
+      - name: Copy gsm8k yaml to lm-eval directory
         run: |
-          cp ./vllm-benchmarks/opencompass/*.py ./opencompass/opencompass/configs
-          pip install datasets==2.18.0
+          pip install ray
+          pip install datasets==2.16.0 transformers==4.50.3 huggingface-hub==0.29.3
+          cp ./vllm-benchmarks/accuracy/gsm8k.yaml ./lm-eval/lm_eval/tasks/gsm8k   
 
-      - name: Run benchmark iteration
-        working-directory: ./vllm-benchmarks
+      - name: Run vllm-project/vllm-ascend Qwen/Qwen2.5-VL-7B-Instruct accuracy test for V0 Engine
+        working-directory: accuracy
+        if: ${{ contains('all,Qwen/Qwen2.5-VL-7B-Instruct', github.event.inputs.models) }}
+        env:
+          VLLM_USE_V1: 0
         run: |
-          bash .elastic/nightly-benchmarks/scripts/run-performance-benchmarks.sh dsafas ssaf fasfas
+          python ./run-accuracy.py --model Qwen/Qwen2.5-VL-7B-Instruct --output /__w/vllm-benchmarks/vllm-benchmarks/vllm-benchmarks/accuracy/result/Qwen2.5-VL-7B-Instruct.md
+          
+      - name: Upload Qwen2.5-VL-7B-Instruct Accuracy Reports
+        uses: actions/upload-artifact@v4
+        if: ${{ contains('all,Qwen/Qwen2.5-VL-7B-Instruct', github.event.inputs.models) }}
+        with:
+          name: Qwen2.5-VL-7B-Instruct-accuracy-reports
+          path: |
+            /__w/vllm-benchmarks/vllm-benchmarks/vllm-benchmarks/accuracy/result/Qwen2.5-VL-7B-Instruct.md
+          if-no-files-found: warn
+          retention-days: 90
+          overwrite: true
+
+      - name: Run vllm-project/vllm-ascend Qwen/Qwen2.5-7B-Instruct accuracy test for V0 Engine
+        working-directory: accuracy
+        if: ${{ contains('all,Qwen/Qwen2.5-7B-Instruct', github.event.inputs.models) }} 
+        env:
+          VLLM_USE_V1: 0
+        run: |
+          python ./run-accuracy.py --model Qwen/Qwen2.5-7B-Instruct --output /__w/vllm-benchmarks/vllm-benchmarks/vllm-benchmarks/accuracy/result/Qwen2.5-7B-Instruct.md
+
+      - name: Upload Qwen2.5-7B-Instruct Accuracy Reports
+        uses: actions/upload-artifact@v4
+        if: ${{ contains('all,Qwen/Qwen2.5-7B-Instruct', github.event.inputs.models) }} 
+        with:
+          name: Qwen2.5-7B-Instruct-accuracy-reports
+          path: |
+            /__w/vllm-benchmarks/vllm-benchmarks/vllm-benchmarks/accuracy/result/Qwen2.5-7B-Instruct.md
+          if-no-files-found: warn
+          retention-days: 90
+          overwrite: true
+
+      - name: Run vllm-project/vllm-ascend meta-llama/Llama-3.1-8B-Instruct accuracy test for V0 Engine
+        working-directory: accuracy
+        if: ${{ contains('all,meta-llama/Llama-3.1-8B-Instruct', github.event.inputs.models) }}
+        env:
+          VLLM_USE_V1: 0
+        run: |
+          python ./run-accuracy.py --model meta-llama/Llama-3.1-8B-Instruct --output /__w/vllm-benchmarks/vllm-benchmarks/vllm-benchmarks/accuracy/result/Llama-3.1-8B-Instruct.md
+      
+      - name: Upload Llama-3.1-8B-Instruct Accuracy Reports
+        uses: actions/upload-artifact@v4
+        if: ${{ contains('all,meta-llama/Llama-3.1-8B-Instruct', github.event.inputs.models) }}
+        with:
+          name: Llama-3.1-8B-Instruct-accuracy-reports
+          path: |
+            /__w/vllm-benchmarks/vllm-benchmarks/vllm-benchmarks/accuracy/result/Llama-3.1-8B-Instruct.md
+          if-no-files-found: warn
+          retention-days: 90
+          overwrite: true
