Update test_single_npu.yaml

diff --git a/.github/workflows/test_single_npu.yaml b/.github/workflows/test_single_npu.yaml
--- a/.github/workflows/test_single_npu.yaml
+++ b/.github/workflows/test_single_npu.yaml
@@ -17,8 +17,8 @@ on:
         required: true
         type: choice
         options:
-          - linux-arm64-npu-4 
-        default: 'linux-arm64-npu-4'
+          - linux-arm64-npu-2
+        default: 'linux-arm64-npu-2'
         description: 'The runner selected to run on'
     
 # Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
@@ -29,9 +29,10 @@ defaults:
     shell: bash -el {0}
 
 jobs:
-  test:
+  test_Qwen2_5_7B_Instruct:
+    if: ${{ contains('all,Qwen/Qwen2.5-7B-Instruct', github.event.inputs.models) }} 
     name: vLLM Ascend accuracy test (self-host)
-    runs-on: ${{ github.event.inputs.runner || 'linux-arm64-npu-4' }}
+    runs-on: ${{ github.event.inputs.runner || 'linux-arm64-npu-2' }}
     timeout-minutes: 1000
     container:
       image: 'ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10'
@@ -82,7 +83,6 @@ jobs:
         uses: actions/checkout@v4
         with:
           repository: vllm-project/vllm
-          ref: v0.7.3
           path: ./vllm-empty
 
       - name: Install vllm-project/vllm from source
@@ -95,7 +95,6 @@ jobs:
         with:
           repository: vllm-project/vllm-ascend
           path: ./vllm-ascend
-          ref: v0.7.3rc2  
           fetch-depth: 0
 
       - name: Install vllm-project/vllm-ascend
@@ -151,15 +150,13 @@ jobs:
 
       - name: Run vllm-project/vllm-ascend Qwen/Qwen2.5-7B-Instruct accuracy test for V0 Engine
         working-directory: accuracy
-        if: ${{ contains('all,Qwen/Qwen2.5-7B-Instruct', github.event.inputs.models) }} 
         env:
           VLLM_USE_V1: 0
         run: |
-          python ./run-accuracy.py --model Qwen/Qwen2.5-7B-Instruct --output /__w/vllm-benchmarks/vllm-benchmarks/vllm-benchmarks/accuracy/result/Qwen2.5-7B-Instruct.md
+          python ./run-accuracy.py --model Qwen/Qwen2.5-7B-Instruct --output $GITHUB_WORKSPACE/vllm-benchmarks/accuracy/result/Qwen2.5-7B-Instruct.md --vllm_ascend_version ${{ github.ref_name }}
 
       - name: Upload Qwen2.5-7B-Instruct Accuracy Reports
         uses: actions/upload-artifact@v4
-        if: ${{ contains('all,Qwen/Qwen2.5-7B-Instruct', github.event.inputs.models) }} 
         with:
           name: ${{ github.ref_name }}-Qwen2.5-7B-Instruct-accuracy-reports
           path: |
@@ -168,17 +165,134 @@ jobs:
           retention-days: 90
           overwrite: true
 
+  test_Llama_3_1_8B_Instruct:
+    if: ${{ contains('all,meta-llama/Llama-3.1-8B-Instruct', github.event.inputs.models) }}
+    name: vLLM Ascend accuracy test (self-host)
+    runs-on: ${{ github.event.inputs.runner || 'linux-arm64-npu-2' }}
+    timeout-minutes: 1000
+    container:
+      image: 'ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10'
+      env:
+        HF_ENDPOINT: https://hf-mirror.com
+        HF_TOKEN: ${{ secrets.HF_TOKEN }}
+        DATASET_SOURCE: ModelScope
+        ES_OM_DOMAIN: ${{ secrets.ES_OM_DOMAIN }}
+        ES_OM_AUTHORIZATION: ${{ secrets.ES_OM_AUTHORIZATION }}
+    steps:
+      - name: Validate branch name
+        id: validate_branch
+        run: |
+          if [[ "${{ github.ref_name }}" =~ -dev$ ]]; then
+            echo "Branch name is valid."
+          else
+            echo "Error: The selected branch does not end with '-dev'."
+            exit 1
+          fi
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.ref_name }}
+
+      - name: Check npu and CANN info
+        run: |
+          npu-smi info
+          cat /usr/local/Ascend/ascend-toolkit/latest/"$(uname -i)"-linux/ascend_toolkit_install.info
+
+      - name: Config mirrors
+        run: |
+          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
+          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
+          apt-get update -y
+          apt install git -y
+          git config --global url."https://gh-proxy.test.osinfra.cn/https://github.com/".insteadOf https://github.com/
+
+      - name: Checkout vllm-project/vllm-ascend repo
+        uses: actions/checkout@v4
+
+      - name: Install system dependencies
+        run: |
+          apt-get -y install `cat packages.txt`
+          apt-get -y install gcc g++ cmake libnuma-dev
+
+      - name: Checkout vllm-project/vllm repo
+        uses: actions/checkout@v4
+        with:
+          repository: vllm-project/vllm
+          path: ./vllm-empty
+
+      - name: Install vllm-project/vllm from source
+        working-directory: ./vllm-empty
+        run: |
+          VLLM_TARGET_DEVICE=empty pip install -e .
+
+      - name: Checkout vllm-project/vllm-ascend repo
+        uses: actions/checkout@v4
+        with:
+          repository: vllm-project/vllm-ascend
+          path: ./vllm-ascend
+          fetch-depth: 0
+
+      - name: Install vllm-project/vllm-ascend
+        working-directory: ./vllm-ascend
+        run: |
+          pip uninstall -y numpy
+          pip install -r requirements-dev.txt
+          pip install -e .
+
+      - name: Install pta
+        run: |
+          if [ ! -d /root/.cache/pta ]; then
+            mkdir -p /root/.cache/pta
+          fi
+
+          if [ ! -f /root/.cache/pta/torch_npu-2.5.1.dev20250320-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl ]; then
+            cd /root/.cache/pta
+            rm -rf pytorch_v2.5.1_py310*
+            wget https://pytorch-package.obs.cn-north-4.myhuaweicloud.com/pta/Daily/v2.5.1/20250320.3/pytorch_v2.5.1_py310.tar.gz
+            tar -zxvf pytorch_v2.5.1_py310.tar.gz
+          fi
+
+          pip install /root/.cache/pta/torch_npu-2.5.1.dev20250320-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
+
+      - name: Checkout EleutherAI/lm-evaluation-harness repo
+        uses: actions/checkout@v4
+        with:
+          repository: EleutherAI/lm-evaluation-harness
+          path: ./lm-eval
+          fetch-depth: 0
+
+      - name: Install EleutherAI/lm-evaluation-harness
+        working-directory: ./lm-eval
+        run: |
+          pip install -e .
+      
+      - name: Checkout nv-action/vllm-benchmarks repo
+        uses: actions/checkout@v4
+        with:
+          repository: nv-action/vllm-benchmarks
+          path: ./vllm-benchmarks
+      
+      - name: Install benchmark dependencies
+        working-directory: ./vllm-benchmarks
+        run: |
+          pip install -r requirements.txt
+
+      - name: Copy gsm8k yaml to lm-eval directory
+        run: |
+          pip install ray
+          pip install datasets==2.16.0 transformers==4.50.3 huggingface-hub==0.29.3
+          cp ./vllm-benchmarks/accuracy/gsm8k.yaml ./lm-eval/lm_eval/tasks/gsm8k   
+
       - name: Run vllm-project/vllm-ascend meta-llama/Llama-3.1-8B-Instruct accuracy test for V0 Engine
         working-directory: accuracy
-        if: ${{ contains('all,meta-llama/Llama-3.1-8B-Instruct', github.event.inputs.models) }}
         env:
           VLLM_USE_V1: 0
         run: |
-          python ./run-accuracy.py --model meta-llama/Llama-3.1-8B-Instruct --output /__w/vllm-benchmarks/vllm-benchmarks/vllm-benchmarks/accuracy/result/Llama-3.1-8B-Instruct.md
+          python ./run-accuracy.py --model meta-llama/Llama-3.1-8B-Instruct --output $GITHUB_WORKSPACE/vllm-benchmarks/accuracy/result/Llama-3.1-8B-Instruct.md --vllm_ascend_version ${{ github.ref_name }}
       
       - name: Upload Llama-3.1-8B-Instruct Accuracy Reports
         uses: actions/upload-artifact@v4
-        if: ${{ contains('all,meta-llama/Llama-3.1-8B-Instruct', github.event.inputs.models) }}
         with:
           name: ${{ github.ref_name }}-Llama-3.1-8B-Instruct-accuracy-reports
           path: |
@@ -187,17 +301,134 @@ jobs:
           retention-days: 90
           overwrite: true
 
+  test_Qwen2_5_VL_7B_Instruct:
+    if: ${{ contains('all,Qwen/Qwen2.5-VL-7B-Instruct', github.event.inputs.models) }}
+    name: vLLM Ascend accuracy test (self-host)
+    runs-on: ${{ github.event.inputs.runner || 'linux-arm64-npu-2' }}
+    timeout-minutes: 1000
+    container:
+      image: 'ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10'
+      env:
+        HF_ENDPOINT: https://hf-mirror.com
+        HF_TOKEN: ${{ secrets.HF_TOKEN }}
+        DATASET_SOURCE: ModelScope
+        ES_OM_DOMAIN: ${{ secrets.ES_OM_DOMAIN }}
+        ES_OM_AUTHORIZATION: ${{ secrets.ES_OM_AUTHORIZATION }}
+    steps:
+      - name: Validate branch name
+        id: validate_branch
+        run: |
+          if [[ "${{ github.ref_name }}" =~ -dev$ ]]; then
+            echo "Branch name is valid."
+          else
+            echo "Error: The selected branch does not end with '-dev'."
+            exit 1
+          fi
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.ref_name }}
+
+      - name: Check npu and CANN info
+        run: |
+          npu-smi info
+          cat /usr/local/Ascend/ascend-toolkit/latest/"$(uname -i)"-linux/ascend_toolkit_install.info
+
+      - name: Config mirrors
+        run: |
+          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
+          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
+          apt-get update -y
+          apt install git -y
+          git config --global url."https://gh-proxy.test.osinfra.cn/https://github.com/".insteadOf https://github.com/
+
+      - name: Checkout vllm-project/vllm-ascend repo
+        uses: actions/checkout@v4
+
+      - name: Install system dependencies
+        run: |
+          apt-get -y install `cat packages.txt`
+          apt-get -y install gcc g++ cmake libnuma-dev
+
+      - name: Checkout vllm-project/vllm repo
+        uses: actions/checkout@v4
+        with:
+          repository: vllm-project/vllm
+          path: ./vllm-empty
+
+      - name: Install vllm-project/vllm from source
+        working-directory: ./vllm-empty
+        run: |
+          VLLM_TARGET_DEVICE=empty pip install -e .
+
+      - name: Checkout vllm-project/vllm-ascend repo
+        uses: actions/checkout@v4
+        with:
+          repository: vllm-project/vllm-ascend
+          path: ./vllm-ascend
+          fetch-depth: 0
+
+      - name: Install vllm-project/vllm-ascend
+        working-directory: ./vllm-ascend
+        run: |
+          pip uninstall -y numpy
+          pip install -r requirements-dev.txt
+          pip install -e .
+
+      - name: Install pta
+        run: |
+          if [ ! -d /root/.cache/pta ]; then
+            mkdir -p /root/.cache/pta
+          fi
+
+          if [ ! -f /root/.cache/pta/torch_npu-2.5.1.dev20250320-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl ]; then
+            cd /root/.cache/pta
+            rm -rf pytorch_v2.5.1_py310*
+            wget https://pytorch-package.obs.cn-north-4.myhuaweicloud.com/pta/Daily/v2.5.1/20250320.3/pytorch_v2.5.1_py310.tar.gz
+            tar -zxvf pytorch_v2.5.1_py310.tar.gz
+          fi
+
+          pip install /root/.cache/pta/torch_npu-2.5.1.dev20250320-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
+
+      - name: Checkout EleutherAI/lm-evaluation-harness repo
+        uses: actions/checkout@v4
+        with:
+          repository: EleutherAI/lm-evaluation-harness
+          path: ./lm-eval
+          fetch-depth: 0
+
+      - name: Install EleutherAI/lm-evaluation-harness
+        working-directory: ./lm-eval
+        run: |
+          pip install -e .
+      
+      - name: Checkout nv-action/vllm-benchmarks repo
+        uses: actions/checkout@v4
+        with:
+          repository: nv-action/vllm-benchmarks
+          path: ./vllm-benchmarks
+      
+      - name: Install benchmark dependencies
+        working-directory: ./vllm-benchmarks
+        run: |
+          pip install -r requirements.txt
+
+      - name: Copy gsm8k yaml to lm-eval directory
+        run: |
+          pip install ray
+          pip install datasets==2.16.0 transformers==4.50.3 huggingface-hub==0.29.3
+          cp ./vllm-benchmarks/accuracy/gsm8k.yaml ./lm-eval/lm_eval/tasks/gsm8k   
+
       - name: Run vllm-project/vllm-ascend Qwen/Qwen2.5-VL-7B-Instruct accuracy test for V0 Engine
         working-directory: accuracy
-        if: ${{ contains('all,Qwen/Qwen2.5-VL-7B-Instruct', github.event.inputs.models) }}
         env:
           VLLM_USE_V1: 0
         run: |
-          python ./run-accuracy.py --model Qwen/Qwen2.5-VL-7B-Instruct --output /__w/vllm-benchmarks/vllm-benchmarks/vllm-benchmarks/accuracy/result/Qwen2.5-VL-7B-Instruct.md
+          python ./run-accuracy.py --model Qwen/Qwen2.5-VL-7B-Instruct --output $GITHUB_WORKSPACE/vllm-benchmarks/accuracy/result/Qwen2.5-VL-7B-Instruct.md --vllm_ascend_version ${{ github.ref_name }}
           
       - name: Upload Qwen2.5-VL-7B-Instruct Accuracy Reports
         uses: actions/upload-artifact@v4
-        if: ${{ contains('all,Qwen/Qwen2.5-VL-7B-Instruct', github.event.inputs.models) }}
         with:
           name: ${{ github.ref_name }}-Qwen2.5-VL-7B-Instruct-accuracy-reports
           path: |
